### PR TITLE
contributor avatar (why not)

### PR DESCRIPTION
**Pull request by teren3ce**

### CODE REVIEW

**Comment by teren3ce** [comment]
screen shot 2018-07-21 at 8 35 35 pm
Redesigned on Figma before actual coding was done with VS Code

**Comment by teren3ce** [comment]
what do you suggest?

**Comment by vikaskyadav** [comment]
Some pulse or swing type may be. or a mix up with a little bounce.

**Comment by teren3ce** [comment]
sharp, i think i like that, also thinking of a pulse effect animation on hover

**Comment by teren3ce** [comment]
I actually thought of that initially, should make that update soon.
but I want to capture as much information as contained on the contributors' page
screen shot 2018-07-24 at 3 28 28 am

**Comment by dvdsgl** [comment]
Maybe just start small with the faces?

Also, it might be nice to do just an ambient animation that cycles everyone who contributed through?

**Comment by teren3ce** [comment]
that feels too much to me, it will no longer be a design based on simplicity
or maybe I don't fully get you?

**Comment by teren3ce** [comment]
also, do u mind collaborating on this with me on figma?https://www.figma.com/file/DwlwB9e1ZRCzbJsccv2fyBkD/Join-Microsoft-Design?node-id=0%3A1

started working on a sidebar view to see all contributors.

**Comment by dvdsgl** [comment]
Sorry, I can't collaborate right now but perhaps someone else will. I suggest prototyping some simple animation in Framer–I was just thinking a subtle line of avatars, maybe they cycle when you hover, translating left where avatars fade out, and fade in from the right.

**Comment by dvdsgl** [comment]
Closing for now.

I think this is really awesome, please feel free to reopen if you fix conflicts and arrive at a final design that you are happy with.

Thank you! Your PR has been noted.

**Pull request closed without merging**
