### PR TITLE
Disable time travel button in time travel mode

### PR DESCRIPTION
**Pull request by d4rekanguok**
(WIP) The relative time travel link is broken in time travel mode (my bad) & should be disabled. I'm trying out these 2 message positions:

#### Toast on click
time-travel-toast

#### Tooltip on hover
time-travel-tooltip

Which one is better, position wise? Suggestion on other ideas are welcome too.

### CODE REVIEW

**Comment by d4rekanguok** [comment]
Right we should handle all other links as well. This is how I'm handling them:

- time travel: will be disabled with a warning toast on click
- external (link to vscode site, figma site, etc.): will open in a new browser tab (set anchor target to _blank)
- internal (e.g if someone makes a page for contributors at `docs/contributors`): the build script will save that page & it should work inside iframe

**Comment by prichodko** [comment]
@d4rekanguok is this PR ready? Looks great, IMO!

**Comment by d4rekanguok** [comment]
@prichodko Thank you! I've just rebase current master to my branch, I think it's ready if you want to merge it

**Comment by prichodko** [comment]
Awesome, thanks!

**Pull request merged**
