### PR TITLE
Add icons for better readability

### PR DESCRIPTION
**Pull request by ravishanker**
Make content easy to grasp just by scanning or skimming

### CODE REVIEW

**Comment by dvdsgl** [comment]
Preview:

image

**Comment by dosyago-coder-0** [comment]
It's a cool idea, but I think it's too much.

On the road to helping people digest the info quickly, I feel it distracts. Maybe that's just me.

But if we are going to do it ~ why not be consistent and put in icons for diversity, openness, and delightful tools? 

As well as icons before PR, email and microsoft.

(*Should this comment be comments on the code?*)

**Comment by ravishanker** [comment]
@dosyago-coder-0 terms like diversity, openness, delightful tools are generic unlike the brand images used for well-known names.

**Comment by prichodko** [comment]
Thanks for the contribution! 

But, IMO, icons just add clutter. I like plain version more. 

Maybe if you are trying to make it look more appealing, try it with emojis? 👀

**Comment by dvdsgl** [comment]
An interesting experiment, but I think the legibility suffers. Thank you for your PR.

**Pull request closed without merging**
