### PR TITLE
Added Time Travel Functionality

### PR DESCRIPTION
**Pull request by georgewritescode**
This commits adds a 'Time Travel Back' link at the bottom of the page.
It looks at the past commits and gets the index.html at that time and inserts it at the bottom of the page. 

It's pretty cool to keep scrolling down and see how the change has changed over time. It keeps going down the commit trail until a change to index.html was made in the commit.

Could have a few improvements but perhaps something we can build upon?

### CODE REVIEW

**Comment by sangeeth96** [comment]
The CSS could be different in the previous commits so it doesn't really make sense to show just the HTML content.

**Comment by georgewritescode** [comment]
Added functionality to keep going down the commit trail until a change was made to index.html.

**Comment by georgewritescode** [comment]
@sangeeth96 Agree with you. Have made a start on fixing that. 
The html page received now loads the relevant style.css from the commit. 
More testing is needed to ensure this is applied.

If anyone wants to join me on this you're welcome.

**Comment by georgewritescode** [comment]
Thanks @vikaskyadav , I've updated the text to make it cleaner. If someone would like to find an icon and place it perhaps at the bottom right of the screen that could work too.

**Comment by dvdsgl** [comment]
This is incredible. I was hoping someone would attempt this!

If you can think of a more durable way to implement, I'd love to merge. Right now the interaction is a bit confusing and I don't have a lot of confidence in the approach to loading the content. The file handling is too fragile, for example.

We could add a build script to create a static directory for each commit under `/docs`? Or maybe there is a way to serve the data from GitHub's raw files?

**Comment by d4rekanguok** [comment]
This is awesome! Something like a slide UI to travel thru time would be amazing.

**Comment by georgewritescode** [comment]
@dvdsgl Agree with your suggestions. I've added a build functionality which downloads the html and css files for every change to index.html and stores them in docs/history. 

Going back in time now displays the name of the commit maker and their commit message.

More changes still to go, currently, the page keeps getting larger as you 'go back in time'. Also the theme button stops working. Whether the styles getting applied is also unclear.

If anyone would like to join in and perhaps make a sidebar with the commits or replace the current page (with the correct CSS applied) rather than adding to the page I think it would work quite well.

**Comment by d4rekanguok** [comment]
@georgewritescode Love the idea, I'll give the sidebar a shot

**Comment by dvdsgl** [comment]
Why not a single directory per commit and keep the historical filenames? Then use an iframe to display the contents of each commit directory.

**Comment by d4rekanguok** [comment]
@georgewritescode @dvdsgl That's what I'm doing as well, except that I'm pulling PRs instead of commits, since that seems to be a bit more meaningful.

Quick update:
time-travel-demo

**Comment by d4rekanguok** [comment]
For the sidebar, I think If we do horizontal, it's possible that the page inside the iframe won't be displayed in full (have to scroll to see full page). Since the website is already well optimized for small width, I think it works well with a vertical sidebar. I would love to revisit & give horizontal a try though.

Corner icon probably works — I'm thinking bottom right fixed, what do you folks think?

**Comment by dvdsgl** [comment]
Maybe a toggle inline with the theme switcher, so we begin to develop a localized control strip.

**Comment by d4rekanguok** [comment]
Sounds great. I'll make a new PR after fixing up some stuff so we can talk more about implementation.

**Comment by georgewritescode** [comment]
@d4rekanguok Great job! This looks fantastic. I love the idea of using Pull Requests rather than commits too. I've merged your PR and given you collaborative access to the repo. Let's make this a reality!

**Comment by dvdsgl** [comment]
Is `npm run build-timetravel` still relevant? It's still in the README.

**Comment by dvdsgl** [comment]
Also, how should people discover this? Perhaps we can change the `Contributed by 34 contributors on GitHub` element to link to this?

**Comment by d4rekanguok** [comment]
@georgewritescode thanks George!! I saw the invite.

@dvdsgl Ah sorry my PR was meant to be a work in progress, I haven't updated the build script & readme yet, will update in a sec. For discovery, perhaps we can rework the `Contributed...` line to include time travel link? i.e `See contributions made by 34 contributors.`?

**Comment by d4rekanguok** [comment]
btw my build.js is running a bit faulty, a few of the PR is missing files 😓

**Comment by dvdsgl** [comment]
I'm eager to merge once conflicts are resolved!

**Comment by d4rekanguok** [comment]
@dvdsgl I've just cleaned it up!

**Comment by dvdsgl** [comment]
Brilliant work, everyone!

**Comment by dvdsgl** [comment]
Oops! Please just prepare another branch with the fix and I will force-push over master real quick.

**Comment by dvdsgl** [comment]
Guys, this is probably the coolest thing I've ever seen happen on GitHub.

**Comment by dvdsgl** [comment]
Or, if there is a way to do this without a rewrite, that would be ideal.

**Comment by d4rekanguok** [comment]
Awesome! It’ll be hard for me to work on this now but I’ll try to work in a rebase in a few hours

**Comment by pmarquees** [comment]
I know this is old, but I found this just now so...

THIS IS SO NICE! 

Open Source <3

**Pull request merged**
