### PR TITLE
Persist theme setting using localStorage

### PR DESCRIPTION
**Pull request by sangeeth96**
Selected theme is now stored inside `localStorage` and used on repeat visits.

### CODE REVIEW

**Comment by dvdsgl** [comment]
There are a few unrelated changes here too.

**Comment by dvdsgl** [comment]
Oops! Accidentally closed.

Please limit changes just to persistence on this PR.

**Comment by sangeeth96** [comment]
@dvdsgl sorry, the editor kicked in. I removed most of the unwanted changes. Could you check to see if it's alright now?

**Comment by sangeeth96** [comment]
Rebased my branch to match the changes made in #84. @dvdsgl

**Comment by dvdsgl** [comment]
`eslint` would have a lot of issues with this JavaScript. Any chance you can add a linter to the new pre-commit hook and address?

**Comment by sangeeth96** [comment]
@dvdsgl Yes, that should be possible. Currently, this is using default Prettier config to format which was introduced in #84. I can look into adding ESLint (with or without Prettier) but do you have any specific preference as to what the rules should be? A baseline like [eslint-config-airbnb](https://www.npmjs.com/package/eslint-config-airbnb)?

**Comment by vikaskyadav** [comment]
@sangeeth96  yeah eslint airbnb config will do

**Comment by dvdsgl** [comment]
Would love to get this in once conflicts are fixed and unrelated changes are dropped. Please reopen if you can update (closing now so we can focus on other PRs ready to merge).

It makes time travel nicer, since the theme will stick across time.

**Pull request closed without merging**
