### PR TITLE
Added a simon game

### PR DESCRIPTION
**Pull request by makeupsomething**
Turn the microsoft logo into a little game of simon. Any suggestions on how to improve are totally welcome.

### CODE REVIEW

**Comment by yangwen2** [comment]
i suggest disabling your IDE's auto format.  The CSS shows it has been entirely changed.  I know it's mostly formatting, but no time to validate....

**Comment by makeupsomething** [comment]
@yangwen2 Thanks for the tip! I've fixed that now

**Comment by makeupsomething** [comment]
Ive added feedback when a user gets a correct answer and a winning condition when the score is greater than 10.

**Comment by dvdsgl** [comment]
Very cool!

Indicating the game sequence by fading tiles is visually an odd choice since you are visually deemphasizing what you intend to emphasize. I'm not sure what would look great, perhaps even blinking the tile would work. I would also animate the visual state change with CSS transitions.

I also suggest accelerating the sequence as it grows.

**Comment by dvdsgl** [comment]
Great progress!

**Comment by makeupsomething** [comment]
@dvdsgl 

Thanks! 🎉 
My last step is to add in some visual indication when the player is wrong and reset the game.

**Comment by dvdsgl** [comment]
Also, rather than lifting a tile to signal that a game is available in the logo, can you just print a hint to the console? Or do a more subtle glimmer on the logo?

**Comment by dvdsgl** [comment]
Amazing! I just tried it and it works! Reasonably challenging too 😄

**Comment by d4rekanguok** [comment]
Awesome! it took me 4 tries to get in the first win

**Pull request merged**
