### PR TITLE
Improved Animations, Content Hierarchy, Readable Links, Logo

### PR DESCRIPTION
**Pull request by benjvmin**
### Improvements
Improved animations so no flickering scroll bar appears when animating. Previously this problem was due to animating the entire body. Instead, it made more sense to add the "move-in" animation with specific animation delays to individual paragraphs to create a beautiful cascading effect on load.

Lightened the background-color by a smidgen. I felt that the original background color was just a tad bit too close to full on black. 

Updated link colors for improved readability. The original color was almost nearly indistinguishable from the body text. Added an electric orange / red color to make them stand out. I kept the original blue hover states. 

### Opinionated Choices
Emphasized mission statement in header by increasing font weight and size to create visual hierarchy to accurately reflect the separation of ```<header></header>``` paragraph and ```<main></main>``` paragraphs. Also added very light horizontal rule and styling to separate main content from header.

Added unobtrusive hover transition for Microsoft logo, and background color of white to provide a clean background that lets the logo stand out.

dev-design

### CODE REVIEW

**Comment by dvdsgl** [comment]
I love it. If you resolve the conflicts and remove the white shape behind the Microsoft logo, I'll accept.

**Comment by benjvmin** [comment]
On it!

**Comment by benjvmin** [comment]
Done! One merge conflict was VScode automatically lowercase-ing a simple hex code. The only conflict that seemed newer to me was the footer change, so I went with what was on master. Cheers!

**Comment by dvdsgl** [comment]
Radical 🏄

**Pull request merged**
