### PR TITLE
Call To Action for apply

### PR DESCRIPTION
**Pull request by ergum**
Call to Action button for apply with the two options: Send email and PR over Github project. With this approach it's more easy to find the main actions for this site. The rock hand ads more fun 😄 

cta-preview

### CODE REVIEW

**Comment by prichodko** [comment]
Thanks for contribution! 

Deployed here: https://join-dev-design-ykhpxxuobn.now.sh

**Comment by dvdsgl** [comment]
Super cool but it's getting quite busy on mobile:

png image

**Comment by ergum** [comment]
Ok @dvdsgl little improve in mobile version like in Desktop mode, avoiding default scroll up behaviour. And adjusting the button sizes to balance them in reduced screen sizes.

cta-mobile

**Comment by dvdsgl** [comment]
The 'sign of the horns' is considered a rude hand gesture in Mediterranean countries. Can you please fine an alternative?

**Comment by ergum** [comment]
As a mediterranean guy I have to say it's true. The detail to be rude is if you see the rear hand side not the front. To be more polite I played with an alternative options, a punch hand (a shape too difficult to recognize and very similar to Cobra Kai...) and a hello hand. More international meaning.

That one:

captura de pantalla 2018-07-26 a las 8 23 37

**Comment by dvdsgl** [comment]
I have to say, this is one of my favorite PRs. I love the visual detail, interaction, and animation.

That said, I don't want to merge it because it feels a bit redundant, and more than we need.

Thank you for your interesting and creative work.

**Comment by ergum** [comment]
It was a pleasure @dvdsgl and @prichodko thanks for your feedback  😄

**Pull request closed without merging**
