### PR TITLE
Corrected theme item off-by-1 pixel error

### PR DESCRIPTION
**Pull request by dosyago-coder-0**
Changing this:

chrome_2018-07-21_14-03-07

into this:

chrome_2018-07-21_14-04-29

### CODE REVIEW

**Comment by dosyago-coder-0** [comment]
I'm not sure. I can test some more.

What problems can you think of?

**Comment by dosyago-coder-0** [comment]
*Just tested in Firefox, Chrome, Safari and Edge.*

@vikaskyadav, looks to be working.

**Comment by vikaskyadav** [comment]
IF it works fine on small screens then we are good to go. 🙌

**Comment by dvdsgl** [comment]
Great!

**Pull request merged**
