### PR TITLE
MSFT logo on console using gradients

### PR DESCRIPTION
**Pull request by sangeeth96**
image

This is how the updated log looks clockwise from top-left: Edge, Firefox, Chrome, Opera. I've also tested it on Chrome Canary and it works there as well. The previous version didn't work when I tested it on Firefox and Edge.

Edge currently has a bug which requires you to reload the page once after you open DevTools for the formatted log to appear.

Also fixed the `<script>` tags which were placed previous inside the `<html>` tags instead of the `<body>` tags.

Let me know if this is alright. IMO, the dark background was a little too aggressive on light BG console. This works well on both light/dark.

### CODE REVIEW

**Comment by reimertz** [comment]
<3

**Comment by dvdsgl** [comment]
Awesome work! Thank you.

**Comment by sangeeth96** [comment]
This was so hard to get right (and I don't know how far along this works). Every browser has its own limitations on how console styles are rendered and what properties are allowed. Plus, don't even get me started on bugs (I'm looking at you, Edge 😛). I wish there was some standard for this to make our lives easy (who doesn't love to fiddle around in a console?).

I should've documented all the things I tried (`box-shadow`, `text-shadow`, `border`...). Maybe I'll be jobless enough to do this again someday I'm free and see how messed up things are with `log`. 😄

**Comment by RayPS** [comment]
The logo is broken in Safari

**Comment by sangeeth96** [comment]
Ah, dang it! I don't unfortunately own a Mac to test it. How does it look there?

On 22-Jul-2018 1:19 PM, Ray <notifications@github.com> wrote:

The logo is broken in Safari

**Comment by RayPS** [comment]
Well, It looks like this:
screen shot 2018-07-22 at 19 35 42

**Comment by RayPS** [comment]
Logging a SVG in console is less tricky than using css gradients. And it's WYSIWYG.
https://hackernoon.com/i-made-a-discovery-svg-and-svg-animations-in-the-js-console-are-doable-6c367c95726a
The MS logo is just as simple as 4 `<rect>` svg tag.

**Comment by RayPS** [comment]
I have made a PR with different implementation: #101

**Pull request merged**
