### PR TITLE
Visual improvements: monospaced font and load animation

### PR DESCRIPTION
**Pull request by vladmoroz**
Visual improvements and some cleanup:
– Changed font to monospaced for a more authentic look
– Added a Fade In animation on page load
– Larger font for better readability
– Larger margins on smaller viewports for better readability
– Minified SVG

screenshot

### CODE REVIEW

**Comment by dvdsgl** [comment]
❤️this!

But can we have the paragraphs back?

**Comment by vladmoroz** [comment]
@dvdsgl Sure, it's a bit more ragged, but still looks good. I also resolved the conflicts.

screenshot-2

**Comment by dvdsgl** [comment]
Brilliant! Perhaps someone else can improve the raggedness–I just liked the punchiness of the separate tweet-length paragraphs 😸

**Comment by dvdsgl** [comment]
Also, think you for including a preview of the result--that was very useful and nobody has thought to do that yet.

**Pull request merged**
