### PR TITLE
Animated gradient text hover

### PR DESCRIPTION
**Pull request by ergum**
Animated gradients are nice. Why not use it also with text hovers?

### CODE REVIEW

**Comment by prichodko** [comment]
Preview - https://join-dev-design-pjmdztvkgl.now.sh

Looking great, however as I am reading (from left to right) the animation looks a bit unnatural (from right to left). What do you think?

**Comment by dvdsgl** [comment]
Super cool! Seems like some colors are missing? Feels biased toward yellow.

**Comment by ergum** [comment]
I tried to adjust the color proportion increasing the background size form 400% to 600% , I used that pattern:
 var(--yellow) 25%,
 var(--green) 50%,
 var(--blue) 75%,
 var(--yellow) 100%

With this approach I need and extra yellow area to avoid a visual jump when activates the :hover state to blend the color property with background-image gradient.

With this subtle fix you can see more time the green and blue colors:

gradient-hover

**Comment by ergum** [comment]
@prichodko done! and fixed some other issues with the current version

**Comment by dvdsgl** [comment]
Awesome!

**Comment by ergum** [comment]
Yeah gradients everywhere 🌈

**Comment by prichodko** [comment]
Thanks!

**Pull request merged**
