### PR TITLE
Make the timetravel buttons look more interactive

### PR DESCRIPTION
**Pull request by alex-page**
Currently the buttons inside the time travel don't look very clickable. I am hoping adding the interactive colour of yellow as a border that changes to the blue on hover should help.

I noticed that there is probably an increased cognitive load with this change and the subtle colors used before may have some merit, so I am happy to discuss this further if it is too intense or too yellow.

As a minimum I would expect the cursor to change to a pointer on hover.

### CODE REVIEW

**Comment by prichodko** [comment]
Thanks for the contribution!  However there was already a similar effort here https://github.com/Microsoft/join-dev-design/pull/120. Maybe you can join the discussion?

**Comment by dabutvin** [comment]
if you want to try these colors over in #120 feel free 😎 

image

**Comment by alex-page** [comment]
Thanks friends I must of missed that i'll take a look 👀

**Comment by alex-page** [comment]
This should be updated to work with #120 nice work @dabutvin 👍

**Pull request closed without merging**
