### PR TITLE
Readme - Git Contributions Instructions

### PR DESCRIPTION
**Pull request by asidelnik**

### CODE REVIEW

**Comment by dvdsgl** [comment]
The bulleting and shell instruction indentation looks a bit haphazard:

image

Can you please use fenced code blocks with `bash` highlighting for console commands?

```bash
$ echo like this please
```

**Comment by prichodko** [comment]
I don't think that describing GitHub flow is something what should be included in our README (it's a _general_ knowledge) and not really a project specific.

If anyone still thinks it should be included, we can link to one of the GitHub's tutorials - https://help.github.com/categories/collaborating-with-issues-and-pull-requests/.

**Comment by asidelnik** [comment]
@dvdsgl - Complete

@prichodko - It's basically for the newbies (like myself - thought I could save them my research time).

I think some "dos & don'ts" instructions are also needed. These are unclear from some closed PRs like [Add icons for better readability](https://github.com/Microsoft/join-dev-design/pull/100)

I think some new branches should be added for more compelling and less legible experiments.

**Comment by dvdsgl** [comment]
Sorry, I'm still not happy with your use of bullets and indentation. See the jagged layout this causes? Unindent your code blocks and you can also probably not use a bullet list for two short phrases.

screen shot 2018-07-25 at 5 07 51 pm

The visualization under `Pull request` is also very confusing. I suggest writing `microsoft/join-dev-design` rather than Microsoft/join-dev-design. I would use a simple unicode left-arrow rather than emoji.

Also, the grammar inconsistent throughout the steps. Step 5, for example, read "**Pull request** - personal repo into Microsoft repo". I would expect this to say something like "*Make a* pull request..." and for there to be pictures of what I have to do or a link to where I can open the pull request, etc.

Please reopen if you can make these changes. For now, I just think this makes things slightly more confusing.

**Pull request closed without merging**
