### PR TITLE
remove time travel from paragraph

### PR DESCRIPTION
**Pull request by mbj36**
It gives 404, time travel should not be in paragraph, should be only in landing page

### CODE REVIEW

**Comment by dvdsgl** [comment]
Well, this removes it but does not add it exclusively to the landing page. Maybe we should just use an absolute path for the link?

**Comment by mbj36** [comment]
@dvdsgl landing page already have such - https://github.com/Microsoft/join-dev-design/blob/master/docs/index.html#L67

**Comment by prichodko** [comment]
Great catch! There is definitely an error after clicking on a time-travel button during _time traveling_. However this PR doesn't fix the issue, because it deletes the line you are referring to.

I agree with @dvdsgl that the best solution would be changing the `href` to `https://microsoft.github.io/join-dev-design/time-travel` and re-building the history.

**Comment by mbj36** [comment]
Actually line wasn't there, it was added by one of the contributors and not sure why it got merged - https://github.com/Microsoft/join-dev-design/commit/dd4b17d62ed6d54415465760b1da0a3fe32c0c20

**Comment by prichodko** [comment]
I am still confused to what you are referring to - it is on landing page. Do you want to remove it from pages in time-travel mode?

**Comment by mbj36** [comment]
Yes, actually time-travel wasn;t there in paragraph - it was added in this commit - https://github.com/Microsoft/join-dev-design/commit/dd4b17d62ed6d54415465760b1da0a3fe32c0c20 which gives 404 error

**Comment by dvdsgl** [comment]
I would recommend disabling the link in time-travel mode. You would likely implement this in `docs/time-travel/{index.html,time-travel.js}`.

I would expect the following to be true:

* Time Travel link remains as-is when viewed from top-level page
* In Time Travel mode, Time Travel link causes a message to display, like "Time travel cannot be opened within time travel mode."
* In Time Travel mode, the appearance of the Time Travel ink is not affected.

Please reopen if you develop this! Sounds useful. Thank you!

**Pull request closed without merging**
