### PR TITLE
Add live server for development

### PR DESCRIPTION
**Pull request by pubudu-ranasinghe**
Added a live reload capability. Can run the server with `npm run dev`

### CODE REVIEW

**Comment by dvdsgl** [comment]
Why not replace the `start` script entirely? Are there any drawbacks to switching?

**Comment by pubudu-ranasinghe** [comment]
Start uses [serve](https://www.npmjs.com/package/serve) package which seems to mimic Now deployment. So I thought it's preferable to have that as well. 
Should I replace it with live server then?

**Comment by dvdsgl** [comment]
Yes, that's what I am wondering. I'd prefer to just use one development server! Let me know what you think is best.

**Comment by pubudu-ranasinghe** [comment]
Updated to use live-server only since `server` package doesn't seem to support watch and live reload.

**Comment by dvdsgl** [comment]
Very useful! Thank you.

**Pull request merged**
