### PR TITLE
change design and optimize css

### PR DESCRIPTION
**Pull request by piensaenpixel**

### CODE REVIEW

**Comment by piensaenpixel** [comment]
## Desktop version
image

## Tablet version
image


## Mobile version
image

**Comment by dvdsgl** [comment]
Love it!

image

**Comment by dvdsgl** [comment]
Also I'd like to keep the console easter egg (#25).

**Comment by dvdsgl** [comment]
And I miss the fun animations from #20

**Comment by dvdsgl** [comment]
Sorry, this repo is changing so rapidly.

**Comment by obarat** [comment]
sweet look :thumbsup:

**Comment by piensaenpixel** [comment]
Done @dvdsgl ;) If you need something else please feel free to ping me :)

**Comment by dvdsgl** [comment]
@piensaenpixel this is great work, thank you very much.

I'm going to close for now, because I want to continue with #73, but I think your designs are great and I appreciate that you explored the responsive scenarios and included previews in the PR.

**Pull request closed without merging**
