### PR TITLE
Add themes

### PR DESCRIPTION
**Pull request by d4rekanguok**
Hello, I thought it'd be cool to be able to change theme! 
Transition between themes, theme select UI on mobile can be done better; and perhaps theme setting could be stored in local storage.

theme-demo

### CODE REVIEW

**Comment by dvdsgl** [comment]
I love it. Can we keep the footer at the bottom, though?

**Comment by d4rekanguok** [comment]
My bad, accidentally removed a closing div statement while doing rebase. Footer's back where it should be now!

**Comment by JideLambo** [comment]
Oh my. I think this is by far one of the most thought out contribution.

**Comment by dvdsgl** [comment]
Amazing, I can't wait to merge this.

Looks like you affected a lot of formatting that's not related to your changes. What editor are you using? Is there any way you can remove those whitespace changes to avoid creating conflicts for the other PRs?

**Comment by dvdsgl** [comment]
Also, maybe place the theme selector in the upper-right corner for now? That will work on mobile in the short term, then perhaps someone else can suggest an improvement.

**Comment by dvdsgl** [comment]
Or centered below the final paragraph would be good.

**Comment by d4rekanguok** [comment]
My bad, I didn't realize that was happening, `"editor.formatOnSave": true` in vscode workspace setting is tripping me up. 
Just updated html format + move the theme selector to suggested position!

**Comment by dvdsgl** [comment]
Awesome work!

**Pull request merged**
