### PR TITLE
Added open graph meta tags

### PR DESCRIPTION
**Pull request by vikaskyadav**

### CODE REVIEW

**Comment by vikaskyadav** [comment]
I need the image link. I will update that too. couldn't find it actually.

**Comment by thinking-twins** [comment]
og:image here ya go:

dev-design open graph image

you need to re-add the og:image tag and add the image to the repo :)

btw. here's the figma file: [OG Figma File](https://www.figma.com/file/SbJ0t3CjO6PbXLCxtHqkNAlE/Join-Dev-Design-OG-Image?node-id=0%3A1)

**Comment by dvdsgl** [comment]
Awesome! Yes, add the image and I'll merge.

**Comment by vikaskyadav** [comment]
which image tag to keep? figma or normal one?

**Comment by thinking-twins** [comment]
everything is fine the way you did it. 
you might want to change the url to: https://microsoft.github.io/join-dev-design/microsoft-og-image.png
since this is the place your image resides once the pull request got merged.

**Comment by dvdsgl** [comment]
👌 thank you! Very good work.

**Pull request merged**
