### PR TITLE
restyled time traveling sidebar and added commit overview

### PR DESCRIPTION
**Pull request by arminbw**
To enhance the browsing ux, I made the following changes to the time traveling sidebar:

* rearranged and restyled its elements to enhance the compositional flow
* added a navigable commit overview
* removed the editor avatar (missing or rather redundant data in this context)
* changed the merge date into a more human-readable format
* changed the EXIT link into a close symbol

time_travel_changes

### CODE REVIEW

**Comment by prichodko** [comment]
Wow! This looks much better, thanks @arminbw. 

Could you fix the capitalization of `pull request` to `Pull request`? Then it's LGTM.

**Comment by arminbw** [comment]
> Could you fix the capitalization of `pull request` to `Pull request`? Then it's LGTM.
Done. :)

**Comment by arminbw** [comment]
@prichodko I reviewed the conflicts with the latest changes ([pull request 136](https://github.com/Microsoft/join-dev-design/pull/136#issue-204497961) by @d4rekanguok). This should be ready to merge now.

**Comment by arminbw** [comment]
I assume this project is dead. It’s a bit sad, that the merge never happened. But it was a fun little experiment!

**Pull request closed without merging**
