### PR TITLE
indent svg file using spaces, remove fill property & add little design detail

### PR DESCRIPTION
**Pull request by unluisco**
we do not need the fill property in svg element because every path element has a fill property.

### CODE REVIEW

**Comment by unluisco** [comment]
I add color brand on hover in footer links.

design detail

**Comment by adrianmg** [comment]
@unluisco I like the idea of the branding! I wonder if we would run into accessibility issues, it doesn't seem to have enough contrast especially on 'Code' and 'GitHub' ?

**Comment by dvdsgl** [comment]
Nice & clean 👌

**Comment by dvdsgl** [comment]
Oops! I did not refresh so I missed the hover colors on links. Please submit another PR to fix 👌

**Comment by unluisco** [comment]
@adrianmg yes, you are right, maybe a background-color would do the work instead of color property.
I would try.

**Pull request merged**
