### PR TITLE
Fix for scroll bar appearing during animation

### PR DESCRIPTION
**Pull request by jimlamb**
Hide vertical overflow to prevent a vertical scrollbar from appearing during the animation.

### CODE REVIEW

**Comment by sangeeth96** [comment]
If someone blows up their font-size or has a small screen, setting `overflow-y: hidden` would just prevent them from seeing the rest of the text.

**Comment by jimlamb** [comment]
@sangeeth96 good catch. It needs an event listener to reset the overflow once the animation finishes.

**Comment by treyhoover** [comment]
I had the same approach initially and then remembered [this technique](https://css-tricks.com/elegant-fix-jumping-scrollbar-issue/) might work as well. I opened #72 but think temporarily hiding the scrollbar during the animation may still be desirable as an additional improvement.

**Comment by jimlamb** [comment]
Just realized this issue was address by an earlier PR.

**Pull request closed without merging**
